table CategoryTable
	lineageTag: ba9e30a0-bb54-4c63-afd1-0bdb903189c9

	column ID
		dataType: int64
		formatString: 0
		lineageTag: cb8320ff-baf4-4e35-9860-b98535d55056
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: ea35a11e-4221-434d-990b-640a1c0ad682
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	partition CategoryTable = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUXJUitWJVjICspyUYmMB", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ID = _t, Category = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ID", Int64.Type}, {"Category", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

